---
title: "Predicting and Analyzing Causes of Delay for Flight Departures"
author: "Shaun Tran"
date: "2023-04-26"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```


```{r}
# Load necessary libraries
library(tidyverse)
library(caret)

# Read in data
data <- read_csv("Detailed_Statistics_Departures1.csv")

# Select relevant columns
data <- data %>%
  select(DelayCarrierMinutes, DelayWeatherMinutes, DelayNationalAviationSystemMinutes, DelaySecurityMinutes, DelayLateAircraftArrivalMinutes, DestinationAirport, DeparturedelayMinutes)

# Rename columns for convenience
colnames(data) <- c("carrier", "weather", "nas", "security", "late_aircraft", "destination", "departure_delay")


```

```{r}
# Split data into training and test sets
set.seed(123)
trainIndex <- createDataPartition(data$departure_delay, p = 0.8, list = FALSE)
trainData  <- data[trainIndex, ]
testData   <- data[-trainIndex, ]
```

```{r}
# Create linear model using least squares method on training data
model <- lm(departure_delay ~ carrier + weather + nas + security + late_aircraft, data = trainData)

# Make predictions on test data
predictions <- predict(model, testData)

# Add predictions to test data
testData$predictions <- predictions

# Plot predictions against actual values using ggplot
ggplot(testData, aes(x = departure_delay, y = predictions)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) + ggtitle("Predition vs Actual Departure Time")

summary(model)
```

```{r}
#model without security
model12 <- lm(departure_delay ~ carrier + weather + nas + late_aircraft, data = trainData)
summary(model12)
```

```{r}
#Removing 0s from the predictor column because we are only looking at when there is a delay in the factors.
data1 <- trainData[trainData$carrier != 0, ] 
data2 <- trainData[trainData$weather != 0, ]
data3 <- trainData[trainData$nas != 0, ]
data4 <- trainData[trainData$security != 0, ]
data5 <- trainData[trainData$late_aircraft != 0, ]
```

```{r}
#data6 is the new dataset that contains only the rows with a delay in at least one predictor
data6 <- data[rowSums(data[c(1, 5)] != 0) > 0,]
set.seed(123)
trainIndex1 <- createDataPartition(data6$departure_delay, p = 0.8, list = FALSE)
trainData1 <- data6[trainIndex1, ]
testData1 <- data6[-trainIndex1, ]
modelgg <- lm(departure_delay ~ carrier + weather + nas + security + late_aircraft, data = trainData1)
predictions1 <- predict(modelgg, testData1)
testData1$predictions1 <- predictions1
ggplot(testData1, aes(x = departure_delay, y = predictions1)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) + ggtitle("Prediction vs Actual Departure Time with New Dataset")


summary(modelgg)
```


```{r}
#Here i did a fitted model without the predictor  security 
mod1 <- lm(departure_delay ~ carrier + weather + nas + late_aircraft, data = trainData)
#anova is a function to analysis the variance, this is to see their F-statistic and P value. 
anova(mod1,model)
```



```{r}
#this function allow us to plot and show the adjusted r square, intercept, slope and p value
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(se=FALSE, method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}



#I plotted one predictor to the response variable at a time using the dataset that i cleaned.
ggplotRegression(lm(data = data1 , departure_delay~carrier))
ggplotRegression(lm(data = data2 , departure_delay~weather))
ggplotRegression(lm(data = data3 , departure_delay~nas))
ggplotRegression(lm(data = data4 , departure_delay~security))
ggplotRegression(lm(data = data5 , departure_delay~late_aircraft))
```


